### ISSUE TITLE
problem generating schema using instructions in readme

### ISSUE THREAD

**Issue by RicSwirrl** [Swirrl/graphql-qb#44]
Reported from a user at Scottish Gov:

Following the instructions to generate the schema using the Voyager, at step 5. I get “SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data”

**Comment by RickMoynihan** [comment]
Just tried this myself.

I think this specific error might be because the user hasn't deleted the text content (`[object Object]`) from the text area before pasting into it.

If you delete the text from the box before you paste you shouldn't get that error anymore; however it looks like the schema we generate is too big to be displayed in voyager directly, so it's not really something we can fix.  Though perhaps we could revise the readme?

What you can do to work around the schema size issue is select a different `QueryRoot`, e.g. `dataset_earnings` to display a subset of the schema, however the `QueryRoot` drop down lists all types in the schema, so you need to be careful to select a dataset rather than another type that's just named `dataset_<something>` which is further down the tree (I've created another issue for this type naming problem #45).
