### ISSUE TITLE
Cannot lock reference period to year quarters

### ISSUE THREAD

**Issue by zeginis** [Swirrl/graphql-qb#52]
I get: Invalid number, expected digit but got: "Q".

```
{dataset_disability_living_allowance{
  
  observations(dimensions:{age:ALL gender:ALL measure_type:RATIO reference_period:2002-Q2 }){
    page(first:1000){
      result{
        reference_area
        reference_period
        ratio
      }
    }
  }
}}
```
I tried also with: reference_period:"2002-Q2":
'Exception applying arguments to field `observations': For argument `dimensions', for input string: \"2002-Q2\"'

**Comment by RickMoynihan** [comment]
Hi Dimitris,

Thanks for reporting.  `2002-Q2` is not an integer, and I believe the currently deployed version expects an integer representing year.  

I believe @lkitching was working on extending `reference_period` to support such things and more but I'm not sure of the status of this work.  I'll ask him when he gets back from lunch.

It's also worth mentioning the demo system we're running is the version at this commit: 06eb082, not the tip of master.  Though master may contain changes to do what you wish, we rolled the version back because of some timeout issues we were seeing during schema generation.

**Comment by RickMoynihan** [comment]
See here for the changes between the deployed version and master: https://github.com/Swirrl/graphql-qb/compare/06eb082e21bace26d7cefdc9fc844c250bfe3b39...master

**Comment by lkitching** [comment]
@RickMoynihan @zeginis - The schema for reference periods has changed in master, they are now specified by either the URI, label or start/end times. This was introduced in 48c187a9e57b40b961f8af2762be8d502bfc730a which it sounds like has not been deployed.

The previous behaviour simply mapped year strings to a ref period URI for the scotland data through a custom scalar type e.g. it mapped the string '2008' to `<"http://reference.data.gov.uk/id/year/2008>`. Only year periods were previously supported. This type was removed in cf5b039890da8ec064494ad7f76f9cb85cd46375

We could support strings like `2002-Q2` by adding another field to the reference period filter schema and then parsing it to the corresponding start/end times within the generated SPARQL query. Alternatively if you know the label is also `2002-Q2` then you can use that, although relying on the existence of the label is probably not ideal.

**Comment by zeginis** [comment]
This has already been fixed. Reference period can be locked at quarters using their URI e.g.

```
{dataset_disability_living_allowance{  
  observations(dimensions:{age:ALL gender:ALL measure_type:RATIO 
    reference_period:{uri:"http://reference.data.gov.uk/id/quarter/2002-Q2"}}){
    page{
      observations{   
      	reference_area {
        	label        
      	}
        ratio       
      }
   }
  }
}}
```
