### ISSUE TITLE
The only dimensions that are allowed to have no codelist are the refArea and refPeriod.

### ISSUE THREAD

**Issue by zeginis** [Swirrl/graphql-qb#70]
And their URIs are harcoded:
- Reference area should be defined as: http://purl.org/linked-data/sdmx/2009/dimension#refArea
- Reference period should be defined as: http://purl.org/linked-data/sdmx/2009/dimension#refPeriod

**Comment by zeginis** [comment]
Since there are no code lists, how are the enums for refArea and refPeriod created?

e.g. I get the follwoing result.
```
{ "area": "9170",
  "fuel_type": "DIESEL",
  "registration_date": "http://reference.data.gov.uk/id/year/1993",
  "vehicle_brand": "VOLVO",
  "vehicle_type": "TRACTOR" }
```

The RDF data looks like this:
```
<rdf:Description rdf:about="http://195.251.218.39:8080/id/9170">
	<rdfs:label xml:lang="en">Municipality of Heraklion</rdfs:label>
	<skos:prefLabel xml:lang="en">Municipality of Heraklion</skos:prefLabel>
	<owl:sameAs rdf:resource="http://dbpedia.org/resource/Irakleio,_Attica"/>
</rdf:Description>
```

And 

`<http://reference.data.gov.uk/id/year/1993> <http://www.w3.org/2000/01/rdf-schema#label> "1993" .`

**Comment by RickMoynihan** [comment]
Hey @zeginis thanks again for this.

I think this is best split into two other issues about handling 2nd order properties on `refArea`#71 and `refPeriod` #72.

The reason the codelists aren't required for these is because of schema bloat, which we have plans to resolve and that is why they don't have ENUMs generated for them.  See my answers beneath these questions for an explanation: https://github.com/Swirrl/graphql-qb/issues/55#issuecomment-348570238

The current "hack" to generate the values you see in the JSON responses is for `refArea` we use the  URI's last path segment (slug).  And for `refPeriod` we're using the URI.

I believe we currently know to skip the ENUMification of these dimensions because the URIs are the sdmx URIs you list above.

Thanks for reporting, basically we need to decide what to represent as 2nd order properties in refArea/refPeriod.

This will mean that these dimensions become further nested in responses e.g.  Instead of:

```
{ "area": "9170",
  "fuel_type": "DIESEL",
  "registration_date": "http://reference.data.gov.uk/id/year/1993",
  "vehicle_brand": "VOLVO",
  "vehicle_type": "TRACTOR" }
```

You'd be able to get something more like:

```
{ "area": {"areacode": "9170"},
  "fuel_type": "DIESEL",
  "registration_date": {"uri": "http://reference.data.gov.uk/id/year/1993", "year": 1993},
  "vehicle_brand": "VOLVO",
  "vehicle_type": "TRACTOR" }
```
