### ISSUE TITLE
Version of runing CubiQL

### ISSUE THREAD

**Issue by zeginis** [Swirrl/graphql-qb#86]
@lkitching @RickMoynihan 
Which version of CubiQL are you using at the public instace http://graphql-qb.publishmydata.com/index.html ?

I have deployed CubiQL locally using the latest commit of the code but I cannot run some queries.
E.g.  [Use start end of time period](http://graphql-qb.publishmydata.com/index.html?query=%7B%0A%20%20dataset_births%20%7B%0A%20%20%20%20observations(dimensions%3A%20%7Bgender%3A%20MALE%2C%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20reference_period%3A%7Bstarts_after%3A%20%20%222000-01-01T00%3A00%3A00Z%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20ends_before%3A%20%222001-01-01T00%3A00%3A00Z%22%7D%7D)%20%7B%0A%20%20%20%20%20%20page(first%3A%2020)%20%7B%0A%20%20%20%20%20%20%20%20result%20%7B%0A%20%20%20%20%20%20%20%20%20%20reference_area%0A%20%20%20%20%20%20%20%20%20%20reference_period%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20start%0A%20%20%20%20%20%20%20%20%20%20%20%20end%0A%20%20%20%20%20%20%20%20%20%20%20%20label%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A)

The error I get is:
```
{
  "errors": [
    {
      "message": "Exception applying arguments to field `observations': For argument `dimensions', input object supplied for argument whose type is not an input object.",
      "query-path": [
        "dataset_births"
      ],
      "locations": [
        {
          "line": 2,
          "column": 17
        }
      ],
      "field": "observations",
      "argument": "dimensions",
      "argument-type": "year"
    }
  ]
}
```

**Comment by RickMoynihan** [comment]
Hi @zeginis yes you're right the deployed version is f70728ad, which is pretty old.

I'll have a look at deploying something newer.

When you get the error on master are you running it with your data, or against the scotlands end point?

**Comment by zeginis** [comment]
Hi @RickMoynihan, I run it against the scotlans end point

**Comment by RickMoynihan** [comment]
@zeginis Hi, that error looks like you're trying to query with a schema targetting the old schema.

I think you now need to query that [like this](http://graphql-qb.publishmydata.com/index.html?query=%7B%0A%20%20dataset_births%20%7B%0A%20%20%20%20observations(dimensions%3A%20%7Bgender%3A%20MALE%2C%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20reference_period%3A%7Bstarts_after%3A%20%20%222000-01-01T00%3A00%3A00Z%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20ends_before%3A%20%222001-01-01T00%3A00%3A00Z%22%7D%7D)%20%7B%0A%20%20%20%20%20%20page(first%3A%2020)%20%7B%0A%20%20%20%20%20%20%20%20observations%20%7B%0A%20%20%20%20%20%20%20%20%20%20reference_area%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20label%0A%20%20%20%20%20%20%20%20%20%20%20%20uri%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20reference_period%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20start%0A%20%20%20%20%20%20%20%20%20%20%20%20end%0A%20%20%20%20%20%20%20%20%20%20%20%20label%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A) however that specific query seems to be raising an error due to a time out just now.

I should also say that I've deployed a new version [0.2.0](https://github.com/Swirrl/graphql-qb/releases/tag/0.2.0) based on the head of master.

**Comment by zeginis** [comment]
@RickMoynihan yes I used the old schema.
The new schema looks a little bit "strange" since we should use "observations" keyword twice (observations/page/observations)

I also get a time out error.

**Comment by RickMoynihan** [comment]
Thanks for posting the timeouts issue.  Closing this one.

**Comment by arekstasiewicz** [comment]
Demo server returns: 
> Cannot query field \`result\` on type \`dataset_earnings_observations_page\`.

using the default example.
